inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - '.pryrc'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
